### ISSUE TITLE
Undefined file Websolute_TransporterReports/js/js-beautify/beautify.min.js

### ISSUE THREAD

**Issue by mtytula** [ghostunicorns/module-webapi-logs#1]
![image](https://user-images.githubusercontent.com/36896606/146145012-a8691516-d743-41f3-9ce4-56a13322d60a.png)

https://github.com/ghostunicorns/module-webapi-logs/blob/main/view/adminhtml/templates/detail.phtml#L60

I think there should an another file, because the module has beautify.min.js file in view/adminhtml/web/js/js-beautify directory.

I've checked it and it works with "GhostUnicorns_WebapiLogs/js/js-beautify/beautify.min"

**Comment by artttj** [comment]
Hi guys, please check my PR:
#2

**Comment by raghuiamsingh** [comment]
Thanks for providing the solution.

**Comment by daniloargentiero** [comment]
https://github.com/ghostunicorns/module-webapi-logs/releases/tag/1.2.0
